export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_EACH_USER = "GET_EACH_USER";
export const GET_EACH_USER_SUCCESS = "GET_EACH_USER_SUCCESS";
export const GET_EACH_USER_ERROR = "GET_EACH_USER_ERROR";